In [2]:
import pandas as pd

# Варіант 8 — Полтава
months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

avg_temp = [38, 36, 34, 36, 46, 56, 60, 48, 36, 36, 44, 44]

# Навчальні дані про середньомісячні опади, мм
precip = [40, 35, 38, 45, 55, 70, 65, 55, 45, 40, 48, 42]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip
})

print("Варіант 8 — Полтава")
display(df)

print("Перші рядки:")
display(df.head())

print("Розмір DataFrame:", df.shape)

print("Типи даних:")
print(df.dtypes)

Варіант 8 — Полтава

   month  avg_temp  precip
0    Січ        38      40
1    Лют        36      35
2    Бер        34      38
3    Кві        36      45
4    Тра        46      55
5    Чер        56      70
6    Лип        60      65
7    Сер        48      55
8    Вер        36      45
9    Жов        36      40
10   Лис        44      48
11   Гру        44      42

Перші рядки:

  month  avg_temp  precip
0   Січ        38      40
1   Лют        36      35
2   Бер        34      38
3   Кві        36      45
4   Тра        46      55

Розмір DataFrame: (12, 3)
Типи даних:
month         str
avg_temp    int64
precip      int64
dtype: object

In [3]:
print("DataFrame з індексом за замовчуванням:")
display(df)

print("Індекс:")
print(df.index)

DataFrame з індексом за замовчуванням:

   month  avg_temp  precip
0    Січ        38      40
1    Лют        36      35
2    Бер        34      38
3    Кві        36      45
4    Тра        46      55
5    Чер        56      70
6    Лип        60      65
7    Сер        48      55
8    Вер        36      45
9    Жов        36      40
10   Лис        44      48
11   Гру        44      42

Індекс:
RangeIndex(start=0, stop=12, step=1)

In [4]:
df_by_month = df.set_index("month")

print("DataFrame з індексом month:")
display(df_by_month)

print("Рядок для місяця Чер:")
display(df_by_month.loc["Чер"])

DataFrame з індексом month:

       avg_temp  precip
month
Січ          38      40
Лют          36      35
Бер          34      38
Кві          36      45
Тра          46      55
Чер          56      70
Лип          60      65
Сер          48      55
Вер          36      45
Жов          36      40
Лис          44      48
Гру          44      42

Рядок для місяця Чер:

avg_temp    56
precip      70
Name: Чер, dtype: int64

In [5]:
df = df_by_month.reset_index()

print("Повернули звичайний індекс:")
display(df)

Повернули звичайний індекс:

   month  avg_temp  precip
0    Січ        38      40
1    Лют        36      35
2    Бер        34      38
3    Кві        36      45
4    Тра        46      55
5    Чер        56      70
6    Лип        60      65
7    Сер        48      55
8    Вер        36      45
9    Жов        36      40
10   Лис        44      48
11   Гру        44      42

In [6]:
df.index = range(1, 13)

print("DataFrame з індексом від 1 до 12:")
display(df)

DataFrame з індексом від 1 до 12:

   month  avg_temp  precip
1    Січ        38      40
2    Лют        36      35
3    Бер        34      38
4    Кві        36      45
5    Тра        46      55
6    Чер        56      70
7    Лип        60      65
8    Сер        48      55
9    Вер        36      45
10   Жов        36      40
11   Лис        44      48
12   Гру        44      42

In [7]:
print("avg_temp для місяців 1–6 через .loc:")
display(df.loc[1:6, "avg_temp"])

avg_temp для місяців 1–6 через .loc:

1    38
2    36
3    34
4    36
5    46
6    56
Name: avg_temp, dtype: int64

In [8]:
print("avg_temp для позицій 0–5 через .iloc:")
display(df.iloc[0:6, 1])

avg_temp для позицій 0–5 через .iloc:

1    38
2    36
3    34
4    36
5    46
6    56
Name: avg_temp, dtype: int64

.loc працює з підписами індексу.
.iloc працює з позиціями рядків.

У нашому випадку індекс 1–12, тому:
.loc[1:6] вибирає рядки з підписами 1, 2, 3, 4, 5, 6.
.iloc[0:6] вибирає перші шість рядків — позиції 0, 1, 2, 3, 4, 5.

Тому результати можуть відрізнятися, якщо індекс не збігається
з позицією рядка.

In [9]:
print("Стовпці month і precip:")
display(df[["month", "precip"]])

Стовпці month і precip:

   month  precip
1    Січ      40
2    Лют      35
3    Бер      38
4    Кві      45
5    Тра      55
6    Чер      70
7    Лип      65
8    Сер      55
9    Вер      45
10   Жов      40
11   Лис      48
12   Гру      42

In [10]:
print("Місяці, де avg_temp > 15:")
display(df.loc[df["avg_temp"] > 15, ["month", "avg_temp"]])

Місяці, де avg_temp > 15:

   month  avg_temp
1    Січ        38
2    Лют        36
3    Бер        34
4    Кві        36
5    Тра        46
6    Чер        56
7    Лип        60
8    Сер        48
9    Вер        36
10   Жов        36
11   Лис        44
12   Гру        44

In [11]:
print("Місяці, де avg_temp > 10 і precip > 50:")

result = df[
    (df["avg_temp"] > 10) &
    (df["precip"] > 50)
]

display(result[["month", "avg_temp", "precip"]])

Місяці, де avg_temp > 10 і precip > 50:

  month  avg_temp  precip
5   Тра        46      55
6   Чер        56      70
7   Лип        60      65
8   Сер        48      55

In [12]:
print("Місяці, де avg_temp < 0 або precip > 80:")

result = df[
    (df["avg_temp"] < 0) |
    (df["precip"] > 80)
]

display(result[["month", "avg_temp", "precip"]])

Місяці, де avg_temp < 0 або precip > 80:

Empty DataFrame
Columns: [month, avg_temp, precip]
Index: []

In [13]:
df["avg_temp_f"] = df["avg_temp"] * 9 / 5 + 32

print("Температура у Фаренгейтах:")
display(df)

Температура у Фаренгейтах:

   month  avg_temp  precip  avg_temp_f
1    Січ        38      40       100.4
2    Лют        36      35        96.8
3    Бер        34      38        93.2
4    Кві        36      45        96.8
5    Тра        46      55       114.8
6    Чер        56      70       132.8
7    Лип        60      65       140.0
8    Сер        48      55       118.4
9    Вер        36      45        96.8
10   Жов        36      40        96.8
11   Лис        44      48       111.2
12   Гру        44      42       111.2

In [14]:
mean_precip = df["precip"].mean()

print("Середнє значення precip:", mean_precip)

Середнє значення precip: 48.166666666666664

In [15]:
df["is_wet"] = df["precip"] > mean_precip

print("Стовпець is_wet:")
display(df[["month", "precip", "is_wet"]])

Стовпець is_wet:

   month  precip  is_wet
1    Січ      40   False
2    Лют      35   False
3    Бер      38   False
4    Кві      45   False
5    Тра      55    True
6    Чер      70    True
7    Лип      65    True
8    Сер      55    True
9    Вер      45   False
10   Жов      40   False
11   Лис      48   False
12   Гру      42   False

In [16]:
def get_season(month_number):
    if month_number in [12, 1, 2]:
        return "зима"
    elif month_number in [3, 4, 5]:
        return "весна"
    elif month_number in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"


df["season"] = df.index.map(get_season)

print("Сезони:")
display(df[["month", "season"]])

Сезони:

   month season
1    Січ   зима
2    Лют   зима
3    Бер  весна
4    Кві  весна
5    Тра  весна
6    Чер   літо
7    Лип   літо
8    Сер   літо
9    Вер  осінь
10   Жов  осінь
11   Лис  осінь
12   Гру   зима

## Письмові відповіді

### 1. Чим відрізняються `.loc[1:6]` і `.iloc[0:6]`?

`.loc` вибирає рядки за підписами індексу, а `.iloc` — за їхніми позиціями. 
Тому `.loc[1:6]` залежить від значень індексу, а `.iloc[0:6]` вибирає перші шість позицій. 
Якщо індекс не збігається з позицією рядка, ці команди можуть повернути різні рядки або різну кількість рядків.

### 2. Чому `and` викликає помилку?

У pandas порівняння `df["avg_temp"] > 10` повертає цілий Series значень True/False. 
Оператор `and` призначений для роботи з одиничними логічними значеннями, тому він не може правильно обробити два Series. 
Для поелементного логічного І в pandas використовується `&`.

Правильно:

`(df["avg_temp"] > 10) & (df["precip"] > 50)`

Для логічного АБО використовується `|`.

### 3. Чим відрізняється формула від `.apply()`?

Обчислюваний стовпець через формулу виконує однакову математичну операцію над усіма значеннями стовпця. 
Наприклад, температура у Фаренгейтах обчислюється векторизованою формулою.

`.apply()` дозволяє застосувати власну функцію до кожного значення. 
Це зручно для складнішої логіки, наприклад визначення сезону за номером місяця.