In [2]:
import pandas as pd

# Практика 3. Tidy Data
# Варіант 8 — Полтава

wide = pd.DataFrame({
    "місто": ["Полтава"],
    "Січ": [77],
    "Лют": [73],
    "Бер": [66],
    "Кві": [56],
    "Тра": [47],
    "Чер": [41],
    "Лип": [37],
    "Сер": [39],
    "Вер": [49],
    "Жов": [63],
    "Лис": [75],
    "Гру": [81]
})

print("Wide-таблиця, варіант 8 — Полтава:")
display(wide)

print("Розмір таблиці:", wide.shape)

Wide-таблиця, варіант 8 — Полтава:

     місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Полтава   77   73   66   56   47   41   37   39   49   63   75   81

Розмір таблиці: (1, 13)

In [3]:
months = [
    "Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
    "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"
]

tidy = wide.melt(
    id_vars="місто",
    value_vars=months,
    var_name="місяць",
    value_name="хмарність"
)

print("Tidy-таблиця:")
display(tidy)

print("Розмір tidy-таблиці:", tidy.shape)

Tidy-таблиця:

      місто місяць  хмарність
0   Полтава    Січ         77
1   Полтава    Лют         73
2   Полтава    Бер         66
3   Полтава    Кві         56
4   Полтава    Тра         47
5   Полтава    Чер         41
6   Полтава    Лип         37
7   Полтава    Сер         39
8   Полтава    Вер         49
9   Полтава    Жов         63
10  Полтава    Лис         75
11  Полтава    Гру         81

Розмір tidy-таблиці: (12, 3)

## Завдання 3. Класифікація змінних

### Місто — номінальна шкала

Стовпець "місто" є номінальним, тому що назви міст є категоріями без природного порядку.

### Місяць — номінальна шкала

У цій таблиці місяць використовується як назва категорії, а не як числова величина, тому для цього набору даних його можна розглядати як номінальну змінну.

### Хмарність — шкала відношень

Стовпець "хмарність" є шкалою відношень, оскільки значення задані у відсотках, мають природний нуль, а співвідношення між значеннями має зміст: 80% хмарності вдвічі більше за 40%.

In [4]:
back = tidy.pivot(
    index="місто",
    columns="місяць",
    values="хмарність"
)

print("Wide-таблиця після pivot:")
display(back)

Wide-таблиця після pivot:

місяць   Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
місто
Полтава   66   49   81   63   56   37   75   73   39   77   47   41

In [5]:
# Переставляємо стовпці в початковому порядку
back = back[months]

# Порівнюємо значення
original_values = wide[months].reset_index(drop=True)
back_values = back.reset_index(drop=True)

print("Чи збігаються значення?")
print(original_values.equals(back_values))

Чи збігаються значення?
True

In [6]:
tidy.to_csv(
    "variant.csv",
    index=False
)

tidy.to_json(
    "variant.json",
    orient="records",
    force_ascii=False
)

print("Файли variant.csv та variant.json створено.")

Файли variant.csv та variant.json створено.

In [7]:
reloaded_csv = pd.read_csv("variant.csv")

print("Дані з CSV:")
display(reloaded_csv)

Дані з CSV:

      місто місяць  хмарність
0   Полтава    Січ         77
1   Полтава    Лют         73
2   Полтава    Бер         66
3   Полтава    Кві         56
4   Полтава    Тра         47
5   Полтава    Чер         41
6   Полтава    Лип         37
7   Полтава    Сер         39
8   Полтава    Вер         49
9   Полтава    Жов         63
10  Полтава    Лис         75
11  Полтава    Гру         81

In [8]:
reloaded_json = pd.read_json("variant.json")

print("Дані з JSON:")
display(reloaded_json)

Дані з JSON:

      місто місяць  хмарність
0   Полтава    Січ         77
1   Полтава    Лют         73
2   Полтава    Бер         66
3   Полтава    Кві         56
4   Полтава    Тра         47
5   Полтава    Чер         41
6   Полтава    Лип         37
7   Полтава    Сер         39
8   Полтава    Вер         49
9   Полтава    Жов         63
10  Полтава    Лис         75
11  Полтава    Гру         81

In [9]:
print(
    "CSV збігається:",
    tidy.equals(reloaded_csv)
)

print(
    "JSON збігається:",
    tidy.equals(reloaded_json)
)

CSV збігається: True
JSON збігається: True

In [10]:
print(open("variant.csv", encoding="utf-8").read())

місто,місяць,хмарність
Полтава,Січ,77
Полтава,Лют,73
Полтава,Бер,66
Полтава,Кві,56
Полтава,Тра,47
Полтава,Чер,41
Полтава,Лип,37
Полтава,Сер,39
Полтава,Вер,49
Полтава,Жов,63
Полтава,Лис,75
Полтава,Гру,81

In [11]:
print(open("variant.json", encoding="utf-8").read())

[{"місто":"Полтава","місяць":"Січ","хмарність":77},{"місто":"Полтава","місяць":"Лют","хмарність":73},{"місто":"Полтава","місяць":"Бер","хмарність":66},{"місто":"Полтава","місяць":"Кві","хмарність":56},{"місто":"Полтава","місяць":"Тра","хмарність":47},{"місто":"Полтава","місяць":"Чер","хмарність":41},{"місто":"Полтава","місяць":"Лип","хмарність":37},{"місто":"Полтава","місяць":"Сер","хмарність":39},{"місто":"Полтава","місяць":"Вер","хмарність":49},{"місто":"Полтава","місяць":"Жов","хмарність":63},{"місто":"Полтава","місяць":"Лис","хмарність":75},{"місто":"Полтава","місяць":"Гру","хмарність":81}]

In [ ]:
# Письмові відповіді

## 1. Чому "місто" — номінальна шкала, а "хмарність" — шкала відношень?

"Місто" є номінальною шкалою, тому що це назва категорії, яка не має числового порядку або значення.

"Хмарність" є шкалою відношень, оскільки вона вимірюється у відсотках і має природний нуль. Тому можна порівнювати співвідношення значень, наприклад 80% — це вдвічі більше за 40%.

## 2. Чому wide-таблиця з місяцями у стовпцях не є tidy?

Wide-таблиця не відповідає принципу tidy data, тому що змінна "місяць" представлена назвами окремих стовпців. Після застосування `melt()` всі місяці стають значеннями одного стовпця "місяць", а значення хмарності — стовпцем "хмарність". У результаті кожен рядок описує одне спостереження.

## 3. Чим CSV відрізняється від JSON?

CSV зберігає таблицю у вигляді рядків і стовпців, де значення зазвичай розділені комами. Це простий табличний формат.

JSON зберігає дані як структуровані об'єкти та масиви. Він краще підходить для передачі структурованих даних між програмами та може зберігати складнішу структуру.