In [1]:
import numpy as np
import pandas as pd

# Практика 4. Чищення набору даних
# Варіант 8 — Полтава
# Базова ціна: 700 грн
# Базова кількість: 4

dirty = pd.DataFrame([
    {"замовлення": 1, "місто": "Полтава",    "товар": "Товар 8", "ціна": 700,        "кількість": 4},
    {"замовлення": 2, "місто": " Полтава ",  "товар": "Товар 8", "ціна": "700 грн",   "кількість": np.nan},
    {"замовлення": 3, "місто": "ПОЛТАВА",    "товар": "Товар 8", "ціна": 700,        "кількість": 5},
    {"замовлення": 4, "місто": "Полтава",    "товар": "Товар 8", "ціна": "700 грн",   "кількість": 3},
    {"замовлення": 5, "місто": " Полтава ",  "товар": "Товар 8", "ціна": 7000,       "кількість": 6},
    {"замовлення": 6, "місто": "ПОЛТАВА",    "товар": "Товар 8", "ціна": 700,        "кількість": np.nan},
    {"замовлення": 7, "місто": "Полтава",    "товар": "Товар 8", "ціна": 700,        "кількість": 2},
    {"замовлення": 8, "місто": "Полтава",    "товар": "Товар 8", "ціна": 700,        "кількість": 4},
])

# Додаємо повний дублікат рядка 8
dirty = pd.concat([dirty, dirty.iloc[[7]]], ignore_index=True)

print("Брудний набір даних:")
display(dirty)

print("Розмір:", dirty.shape)

Брудний набір даних:

   замовлення      місто    товар     ціна  кількість
0           1    Полтава  Товар 8      700        4.0
1           2   Полтава   Товар 8  700 грн        NaN
2           3    ПОЛТАВА  Товар 8      700        5.0
3           4    Полтава  Товар 8  700 грн        3.0
4           5   Полтава   Товар 8     7000        6.0
5           6    ПОЛТАВА  Товар 8      700        NaN
6           7    Полтава  Товар 8      700        2.0
7           8    Полтава  Товар 8      700        4.0
8           8    Полтава  Товар 8      700        4.0

Розмір: (9, 5)

In [2]:
print("Кількість пропусків у кожному стовпці:")
print(dirty.isna().sum())

Кількість пропусків у кожному стовпці:
замовлення    0
місто         0
товар         0
ціна          0
кількість     2
dtype: int64

In [3]:
median_quantity = dirty["кількість"].median()

print("Медіана кількості:", median_quantity)

dirty["кількість"] = dirty["кількість"].fillna(median_quantity)

print("Після заповнення пропусків:")
display(dirty)

Медіана кількості: 4.0
Після заповнення пропусків:

   замовлення      місто    товар     ціна  кількість
0           1    Полтава  Товар 8      700        4.0
1           2   Полтава   Товар 8  700 грн        4.0
2           3    ПОЛТАВА  Товар 8      700        5.0
3           4    Полтава  Товар 8  700 грн        3.0
4           5   Полтава   Товар 8     7000        6.0
5           6    ПОЛТАВА  Товар 8      700        4.0
6           7    Полтава  Товар 8      700        2.0
7           8    Полтава  Товар 8      700        4.0
8           8    Полтава  Товар 8      700        4.0

In [4]:
print("Кількість пропусків після очищення:")
print(dirty.isna().sum())

Кількість пропусків після очищення:
замовлення    0
місто         0
товар         0
ціна          0
кількість     0
dtype: int64

In [5]:
print("Повні дублікати:")
display(dirty[dirty.duplicated()])

Повні дублікати:

   замовлення    місто    товар ціна  кількість
8           8  Полтава  Товар 8  700        4.0

In [6]:
print("Повні дублікати:")
display(dirty[dirty.duplicated()])

Повні дублікати:

   замовлення    місто    товар ціна  кількість
8           8  Полтава  Товар 8  700        4.0

In [7]:
print("Дублікати за основними полями:")

duplicates_subset = dirty[
    dirty.duplicated(
        subset=["місто", "товар", "ціна", "кількість"],
        keep=False
    )
]

display(duplicates_subset)

Дублікати за основними полями:

   замовлення    місто    товар ціна  кількість
0           1  Полтава  Товар 8  700        4.0
7           8  Полтава  Товар 8  700        4.0
8           8  Полтава  Товар 8  700        4.0

In [8]:
dirty = dirty.drop_duplicates()

print("Після видалення дубліката:")
display(dirty)

print("Кількість рядків:", len(dirty))

Після видалення дубліката:

   замовлення      місто    товар     ціна  кількість
0           1    Полтава  Товар 8      700        4.0
1           2   Полтава   Товар 8  700 грн        4.0
2           3    ПОЛТАВА  Товар 8      700        5.0
3           4    Полтава  Товар 8  700 грн        3.0
4           5   Полтава   Товар 8     7000        6.0
5           6    ПОЛТАВА  Товар 8      700        4.0
6           7    Полтава  Товар 8      700        2.0
7           8    Полтава  Товар 8      700        4.0

Кількість рядків: 8

In [9]:
print(dirty.dtypes)

замовлення      int64
місто             str
товар             str
ціна           object
кількість     float64
dtype: object

In [11]:
dirty["ціна"] = (
    dirty["ціна"]
    .astype(str)
    .str.replace(" грн", "", regex=False)
    .astype(float)
)

print("Тип ціни після очищення:")
print(dirty["ціна"].dtype)

Тип ціни після очищення:
float64

In [12]:
dirty["місто"] = (
    dirty["місто"]
    .str.strip()
    .str.lower()
    .replace({
        "полтава": "Полтава"
    })
)

print("Унікальні значення міста:")
print(dirty["місто"].unique())

Унікальні значення міста:
<StringArray>
['Полтава']
Length: 1, dtype: str

In [13]:
q1 = dirty["ціна"].quantile(0.25)
q3 = dirty["ціна"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

print("Q1 =", q1)
print("Q3 =", q3)
print("IQR =", iqr)
print("Нижня межа =", lower)
print("Верхня межа =", upper)

Q1 = 700.0
Q3 = 700.0
IQR = 0.0
Нижня межа = 700.0
Верхня межа = 700.0

In [14]:
outliers = dirty[
    (dirty["ціна"] < lower) |
    (dirty["ціна"] > upper)
]

print("Значення поза межами IQR:")
display(outliers)

Значення поза межами IQR:

   замовлення    місто    товар    ціна  кількість
4           5  Полтава  Товар 8  7000.0        6.0

In [15]:
dirty_clean = dirty[
    (dirty["ціна"] >= lower) &
    (dirty["ціна"] <= upper)
].copy()

print("Очищений набір:")
display(dirty_clean)

Очищений набір:

   замовлення    місто    товар   ціна  кількість
0           1  Полтава  Товар 8  700.0        4.0
1           2  Полтава  Товар 8  700.0        4.0
2           3  Полтава  Товар 8  700.0        5.0
3           4  Полтава  Товар 8  700.0        3.0
5           6  Полтава  Товар 8  700.0        4.0
6           7  Полтава  Товар 8  700.0        2.0
7           8  Полтава  Товар 8  700.0        4.0

In [16]:
print("Кількість рядків після очищення:", len(dirty_clean))
print("Унікальні міста:", dirty_clean["місто"].unique())
print("Пропуски:")
print(dirty_clean.isna().sum())
print("Тип ціни:", dirty_clean["ціна"].dtype)

Кількість рядків після очищення: 7
Унікальні міста: <StringArray>
['Полтава']
Length: 1, dtype: str
Пропуски:
замовлення    0
місто         0
товар         0
ціна          0
кількість     0
dtype: int64
Тип ціни: float64

In [17]:
print("=== ФІНАЛЬНИЙ ОЧИЩЕНИЙ НАБІР ===")

display(dirty_clean)

print("Форма:", dirty_clean.shape)
print("Типи даних:")
print(dirty_clean.dtypes)

=== ФІНАЛЬНИЙ ОЧИЩЕНИЙ НАБІР ===

   замовлення    місто    товар   ціна  кількість
0           1  Полтава  Товар 8  700.0        4.0
1           2  Полтава  Товар 8  700.0        4.0
2           3  Полтава  Товар 8  700.0        5.0
3           4  Полтава  Товар 8  700.0        3.0
5           6  Полтава  Товар 8  700.0        4.0
6           7  Полтава  Товар 8  700.0        2.0
7           8  Полтава  Товар 8  700.0        4.0

Форма: (7, 5)
Типи даних:
замовлення      int64
місто             str
товар             str
ціна          float64
кількість     float64
dtype: object