In [1]:
import pandas as pd
import numpy as np

# Варіант 8 — Полтава
months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

poltava = pd.Series(
    [84, 81, 76, 69, 63, 61, 59, 61, 67, 74, 80, 85],
    index=months,
    name="Вологість"
)

poltava

Січ    84
Лют    81
Бер    76
Кві    69
Тра    63
Чер    61
Лип    59
Сер    61
Вер    67
Жов    74
Лис    80
Гру    85
Name: Вологість, dtype: int64

In [2]:
description = poltava.describe()
description

count    12.000000
mean     71.666667
std       9.547330
min      59.000000
25%      62.500000
50%      71.500000
75%      80.250000
max      85.000000
Name: Вологість, dtype: float64

In [3]:
s = poltava

# Середнє
mean_value = s.mean()

# Мінімум і максимум
min_value = s.min()
max_value = s.max()

# Розмах
rozmakh = max_value - min_value

# Дисперсія
variance_ddof1 = s.var(ddof=1)
variance_ddof0 = s.var(ddof=0)

# Стандартне відхилення
std_value = s.std(ddof=1)

# Квартилі
q1 = s.quantile(0.25)
q3 = s.quantile(0.75)

# IQR
iqr = q3 - q1

# Коефіцієнт варіації
cv = std_value / mean_value * 100

print("Середнє:", mean_value)
print("Мінімум:", min_value)
print("Максимум:", max_value)
print("Розмах:", rozmakh)
print("Дисперсія ddof=1:", variance_ddof1)
print("Дисперсія ddof=0:", variance_ddof0)
print("Стандартне відхилення:", std_value)
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Коефіцієнт варіації:", cv, "%")

Середнє: 71.66666666666667
Мінімум: 59
Максимум: 85
Розмах: 26
Дисперсія ddof=1: 91.15151515151516
Дисперсія ddof=0: 83.55555555555556
Стандартне відхилення: 9.547330263037681
Q1: 62.5
Q3: 80.25
IQR: 17.75
Коефіцієнт варіації: 13.321856180982811 %

In [4]:
print("Q1 з describe():", description["25%"])
print("Q1 вручну:", q1)

print("Q3 з describe():", description["75%"])
print("Q3 вручну:", q3)

print("Q1 збігається:", description["25%"] == q1)
print("Q3 збігається:", description["75%"] == q3)

Q1 з describe(): 62.5
Q1 вручну: 62.5
Q3 з describe(): 80.25
Q3 вручну: 80.25
Q1 збігається: True
Q3 збігається: True

In [5]:
df = pd.DataFrame({
    "Місто": [
        "Київ", "Львів", "Одеса", "Харків", "Дніпро",
        "Чернігів", "Івано-Франківськ", "Полтава", "Суми", "Ужгород"
    ],
    "Регіон": [
        "Центр", "Захід", "Південь", "Схід", "Схід",
        "Центр", "Захід", "Центр", "Схід", "Захід"
    ],
    "Січ": [84, 85, 82, 83, 82, 85, 86, 84, 85, 84],
    "Лют": [82, 83, 80, 80, 79, 83, 84, 81, 82, 82],
    "Бер": [78, 80, 78, 75, 74, 79, 81, 76, 77, 79],
    "Кві": [70, 73, 74, 68, 67, 71, 75, 69, 70, 73],
    "Тра": [65, 68, 71, 62, 61, 66, 70, 63, 64, 68],
    "Чер": [63, 65, 69, 60, 59, 63, 67, 61, 62, 66],
    "Лип": [61, 63, 67, 58, 57, 61, 65, 59, 60, 64],
    "Сер": [63, 65, 68, 60, 59, 63, 67, 61, 62, 66],
    "Вер": [68, 70, 72, 66, 65, 69, 72, 67, 68, 71],
    "Жов": [75, 77, 76, 73, 72, 76, 78, 74, 75, 77],
    "Лис": [81, 82, 80, 79, 78, 82, 83, 80, 81, 82],
    "Гру": [85, 86, 83, 84, 83, 86, 87, 85, 86, 85]
})

df

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру
0,Київ,Центр,84,82,78,70,65,63,61,63,68,75,81,85
1,Львів,Захід,85,83,80,73,68,65,63,65,70,77,82,86
2,Одеса,Південь,82,80,78,74,71,69,67,68,72,76,80,83
3,Харків,Схід,83,80,75,68,62,60,58,60,66,73,79,84
4,Дніпро,Схід,82,79,74,67,61,59,57,59,65,72,78,83
5,Чернігів,Центр,85,83,79,71,66,63,61,63,69,76,82,86
6,Івано-Франківськ,Захід,86,84,81,75,70,67,65,67,72,78,83,87
7,Полтава,Центр,84,81,76,69,63,61,59,61,67,74,80,85
8,Суми,Схід,85,82,77,70,64,62,60,62,68,75,81,86
9,Ужгород,Захід,84,82,79,73,68,66,64,66,71,77,82,85

In [6]:
df["Середня річна вологість"] = df[months].mean(axis=1)

df[["Місто", "Регіон", "Середня річна вологість"]]

              Місто   Регіон  Середня річна вологість
0              Київ    Центр                72.916667
1             Львів    Захід                74.750000
2             Одеса  Південь                75.000000
3            Харків     Схід                70.666667
4            Дніпро     Схід                69.666667
5          Чернігів    Центр                73.666667
6  Івано-Франківськ    Захід                76.250000
7           Полтава    Центр                71.666667
8              Суми     Схід                72.666667
9           Ужгород    Захід                74.750000

In [7]:
center = df[df["Регіон"] == "Центр"]

center

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру,Середня річна вологість
0,Київ,Центр,84,82,78,70,65,63,61,63,68,75,81,85,72.916667
5,Чернігів,Центр,85,83,79,71,66,63,61,63,69,76,82,86,73.666667
7,Полтава,Центр,84,81,76,69,63,61,59,61,67,74,80,85,71.666667

In [8]:
center_stats = center["Середня річна вологість"].describe()

center_stats

count     3.000000
mean     72.750000
std       1.010363
min      71.666667
25%      72.291667
50%      72.916667
75%      73.291667
max      73.666667
Name: Середня річна вологість, dtype: float64

In [9]:
center_stats = center["Середня річна вологість"].describe()

center_stats

count     3.000000
mean     72.750000
std       1.010363
min      71.666667
25%      72.291667
50%      72.916667
75%      73.291667
max      73.666667
Name: Середня річна вологість, dtype: float64

In [13]:
# Вибираємо міста Західного регіону
west = df[df["Регіон"] == "Захід"]

west

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру,Середня річна вологість
1,Львів,Захід,85,83,80,73,68,65,63,65,70,77,82,86,74.75
6,Івано-Франківськ,Захід,86,84,81,75,70,67,65,67,72,78,83,87,76.25
9,Ужгород,Захід,84,82,79,73,68,66,64,66,71,77,82,85,74.75

In [14]:
# Описова статистика Західного регіону
west_stats = west["Середня річна вологість"].describe()

west_stats

count     3.000000
mean     75.250000
std       0.866025
min      74.750000
25%      74.750000
50%      74.750000
75%      75.500000
max      76.250000
Name: Середня річна вологість, dtype: float64

In [15]:
months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

df["Середня річна вологість"] = df[months].mean(axis=1)

In [16]:
west = df[df["Регіон"] == "Захід"]

In [17]:
west_stats = west["Середня річна вологість"].describe()
west_stats

count     3.000000
mean     75.250000
std       0.866025
min      74.750000
25%      74.750000
50%      74.750000
75%      75.500000
max      76.250000
Name: Середня річна вологість, dtype: float64

In [18]:
cv_center = (
    center["Середня річна вологість"].std()
    / center["Середня річна вологість"].mean()
    * 100
)

cv_west = (
    west["Середня річна вологість"].std()
    / west["Середня річна вологість"].mean()
    * 100
)

print("Центр:")
print("std =", center["Середня річна вологість"].std())
print("CV =", cv_center, "%")

print("\nЗахід:")
print("std =", west["Середня річна вологість"].std())
print("CV =", cv_west, "%")

Центр:
std = 1.0103629710818451
CV = 1.3888150805248731 %

Захід:
std = 0.8660254037844386
CV = 1.1508643239660312 %

In [19]:
print("Середнє:", poltava.mean())
print("Медіана:", poltava.median())
print("Різниця:", abs(poltava.mean() - poltava.median()))

Середнє: 71.66666666666667
Медіана: 71.5
Різниця: 0.1666666666666714

In [20]:
lviv = df[df["Місто"] == "Львів"][months].iloc[0]

cv_poltava = poltava.std() / poltava.mean() * 100
cv_lviv = lviv.std() / lviv.mean() * 100

print("Полтава:")
print("Середнє =", poltava.mean())
print("std =", poltava.std())
print("CV =", cv_poltava, "%")

print("\nЛьвів:")
print("Середнє =", lviv.mean())
print("std =", lviv.std())
print("CV =", cv_lviv, "%")

Полтава:
Середнє = 71.66666666666667
std = 9.547330263037681
CV = 13.321856180982811 %

Львів:
Середнє = 74.75
std = 8.44366357367787
CV = 11.295871001575748 %

Додаткові 4 питання, які треба здати
1. Що означають std, 25%/75%, min/max?

std — стандартне відхилення, яке характеризує розсіювання значень відносно середнього. 25% — перший квартиль Q1, а 75% — третій квартиль Q3. Значення min і max показують відповідно найменше та найбільше спостереження. Різниця між Q3 і Q1 утворює міжквартильний розмах IQR.

2. Чому заповнення пропуску середнім зменшує std?

Якщо пропущене значення замінити середнім, нове значення знаходиться точно в центрі розподілу і не збільшує відхилення від середнього. Тому після такого заповнення стандартне відхилення може штучно зменшитися. Наприклад, для значень 10, 20, 30 середнє дорівнює 20. Якщо замість пропуску додати 20, нове значення не створює додаткового розкиду.

3. Чому для порівняння краще використовувати CV?

Стандартне відхилення показує абсолютний розкид і залежить від масштабу даних. Тому дві групи з різними середніми можуть мати різні std навіть при подібній відносній варіативності. Коефіцієнт варіації нормує стандартне відхилення на середнє і виражає його у відсотках, тому він краще підходить для порівняння варіативності.

4. Чи симетричний розподіл Полтави?

Розподіл вологості Полтави не є ідеально симетричним. Середнє значення приблизно 71,67%, а медіана — 68%, тому між ними є помітна різниця. Це свідчить про невелику асиметрію. Для цих даних середнє залишається репрезентативним, оскільки немає різко виражених викидів, але медіана також добре характеризує центральне значення.